/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ppdbkalsel;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Edwin Yosua<2110010382>
 */
public class MenuPendaftaran extends javax.swing.JFrame {

    private static final String JDBC_URL = "jdbc:mysql://localhost:3306/dbpendaftaran";

    public MenuPendaftaran() {
        initComponents();
        
        //disable edit by mouse click
        tableSekolah.setDefaultEditor(Object.class, null);
        tableSiswa.setDefaultEditor(Object.class,null);
        
        loadDataTableSekolah();
        loadDataTableSiswa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtNisn = new javax.swing.JTextField();
        edtSekolah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSekolah = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        edtCari = new javax.swing.JTextField();
        cbxCari = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNamaSiswa = new javax.swing.JTextField();
        edtNamaSekolah = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setText("NISN");

        jLabel2.setText("ID SEKOLAH");

        edtNisn.setEnabled(false);

        edtSekolah.setEnabled(false);

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSiswa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSiswa);

        tableSekolah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSekolah.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableSekolah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSekolahMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSekolah);

        jLabel3.setText("CARI DATA");

        edtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCariKeyPressed(evt);
            }
        });

        cbxCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nisn_siswa", "nama_siswa", "id_sekolah", "nama_sekolah" }));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel4.setText("NAMA SISWA");

        jLabel5.setText("NAMA SEKOLAH");

        edtNamaSiswa.setEnabled(false);

        edtNamaSekolah.setToolTipText("");
        edtNamaSekolah.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edtNisn)
                        .addComponent(edtSekolah)
                        .addComponent(edtNamaSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(edtNamaSekolah))
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbxCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtCari))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(edtNisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtNamaSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(edtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKembali)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        edtNisn.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(),0).toString());
        edtNamaSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void tableSekolahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSekolahMouseClicked
        edtSekolah.setText(tableSekolah.getValueAt(tableSekolah.getSelectedRow(),0).toString());
        edtNamaSekolah.setText(tableSekolah.getValueAt(tableSekolah.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tableSekolahMouseClicked

    private void edtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCariKeyPressed
        
        try {
            String sql_comm;
            if(cbxCari.getSelectedItem().toString().equalsIgnoreCase("nisn_siswa") ||
               cbxCari.getSelectedItem().toString().equalsIgnoreCase("nama_siswa")) {
                
                sql_comm = "SELECT * FROM tb_siswa WHERE " 
                + cbxCari.getSelectedItem().toString() +
                " LIKE '%" + edtCari.getText() + "%'";
                
                hasilCariTableSiswaShow(cariData(sql_comm));
                
            }else if(cbxCari.getSelectedItem().toString().equalsIgnoreCase("id_sekolah") ||
                     cbxCari.getSelectedItem().toString().equalsIgnoreCase("nama_sekolah")) {
                
                sql_comm = "SELECT * FROM tb_sekolah WHERE " 
                + cbxCari.getSelectedItem().toString() +
                " LIKE '%" + edtCari.getText() + "%'";
                
                hasilCariTableSekolahShow(cariData(sql_comm));
            } 
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuPendaftaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edtCariKeyPressed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuPendaftaran.this.dispose();
        new MenuUtama().show();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        
        String sql_input = "INSERT INTO tb_daftar VALUES('"+edtNisn.getText()+
        "','" + edtSekolah.getText() +
        "','" + edtNamaSiswa.getText() +
        "','" + edtNamaSekolah.getText() + "')";
           
        try {
            inputEditData(sql_input);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MenuPendaftaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    
    
    //Input data dari form ke Database MySql
    private void inputEditData(String sql_comm) throws SQLException, ClassNotFoundException {              
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection conn = (Connection) DriverManager.getConnection(JDBC_URL,"root","")) {
                Statement st = (Statement)conn.createStatement();
                st.executeUpdate(sql_comm);
                JOptionPane.showMessageDialog(null, "Simpan Sukses");
            }
        }catch (SQLException | ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
    }
    
    //tampilkan data dari tb_sekolah ke table
    private void loadDataTableSekolah() {
        Object header[] = {"ID SEKOLAH", "NAMA SEKOLAH", "JENIS SEKOLAH", "ALAMAT SEKOLAH"};
        String sql_data = "SELECT * FROM tb_sekolah";
        DefaultTableModel data = new DefaultTableModel(null, header);
        
        tableSekolah.setModel(data);

        TableColumnModel columns = tableSekolah.getColumnModel();
        columns.getColumn(0).setMinWidth(50);
        columns.getColumn(1).setMinWidth(150);
        columns.getColumn(2).setMinWidth(100);
        columns.getColumn(3).setMinWidth(100);

        try {
            Connection kon = MysqlKonek.koneksiDb();
            Statement st = (Statement) kon.createStatement();
            ResultSet rs = st.executeQuery(sql_data);
            while (rs.next()) {
                String d1 = rs.getString(1);
                String d2 = rs.getString(2);
                String d3 = rs.getString(3);
                String d4 = rs.getString(4);


                String d[] = {d1, d2, d3, d4};
                data.addRow(d);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //tampilkan data dari tb_siswa ke table
    private void loadDataTableSiswa() {
        Object header[] = {"NISN", "NAMA", "JENIS KELAMIN","TANGGAL LAHIR", "TEMPAT LAHIR", "ALAMAT SISWA", "NIK ORTU", "NAMA ORTU"};
        String sql_data = "SELECT * FROM tb_siswa";
        DefaultTableModel data = new DefaultTableModel(null, header);
        
        tableSiswa.setModel(data);

        TableColumnModel columns = tableSiswa.getColumnModel();
        columns.getColumn(0).setMinWidth(50);
        columns.getColumn(1).setMinWidth(150);
        columns.getColumn(2).setMinWidth(100);
        columns.getColumn(3).setMinWidth(100);
        columns.getColumn(4).setMinWidth(150);
        columns.getColumn(5).setMinWidth(150);
        columns.getColumn(6).setMinWidth(50);
        columns.getColumn(7).setMinWidth(150);

        try {
            Connection kon = MysqlKonek.koneksiDb();
            Statement st = (Statement) kon.createStatement();
            ResultSet rs = st.executeQuery(sql_data);
            while (rs.next()) {
                String d1 = rs.getString(1);
                String d2 = rs.getString(2);
                String d3 = rs.getString(3);
                String d4 = rs.getString(4);
                String d5 = rs.getString(5);
                String d6 = rs.getString(6);
                String d7 = rs.getString(7);
                String d8 = rs.getString(8);

                String d[] = {d1, d2, d3, d4, d5, d6, d7, d8};
                data.addRow(d);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //Untuk eksekusi sql command pencari data
    private ResultSet cariData(String sql_comm) throws SQLException {
        Connection conn = MysqlKonek.koneksiDb();
        Statement st = (Statement) conn.createStatement();
        ResultSet rs = st.executeQuery(sql_comm);
        return rs;
    }
    
    //tampilkan hasil pencarian di table Siswa
    private void hasilCariTableSiswaShow(ResultSet rs) throws SQLException {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NISN SISWA");
        model.addColumn("NAMA SISWA");
        model.addColumn("JENIS KELAMIN");
        model.addColumn("TANGGAL LAHIR");
        model.addColumn("TEMPAT LAHIR");
        model.addColumn("ALAMAT SISWA");
        model.addColumn("NIK ORTU");
        model.addColumn("NAMA ORTU");              
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        model.setRowCount(0);

        while(rs.next()) {
            Object [] data = {
                rs.getString("nisn_siswa"),
                rs.getString("nama_siswa"),
                rs.getString("jk"),
                rs.getString("tanggal_lahir"),
                rs.getString("tempat_lahir"),
                rs.getString("alamat_siswa"),
                rs.getString("nik_ortu"),
                rs.getString("nama_ortu")
            }; 
            model.addRow(data);
            tableSiswa.setModel(model);
        }
    }
    
    //tampilkan hasil pencarian di table Sekolah
    private void hasilCariTableSekolahShow(ResultSet rs) throws SQLException {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID SEKOLAH");
        model.addColumn("NAMA SEKOLAH");
        model.addColumn("JENIS SEKOLAH");
        model.addColumn("ALAMAT SEKOLAH");            
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        model.setRowCount(0);

        while(rs.next()) {
            Object [] data = {
                rs.getString("id_sekolah"),
                rs.getString("nama_sekolah"),
                rs.getString("jenis_sekolah"),
                rs.getString("alamat_sekolah")
            }; 
            model.addRow(data);
            tableSekolah.setModel(model);
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxCari;
    private javax.swing.JTextField edtCari;
    private javax.swing.JTextField edtNamaSekolah;
    private javax.swing.JTextField edtNamaSiswa;
    private javax.swing.JTextField edtNisn;
    private javax.swing.JTextField edtSekolah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableSekolah;
    private javax.swing.JTable tableSiswa;
    // End of variables declaration//GEN-END:variables
}
